### PR TITLE
Introduce coverage worker

### LINKED ISSUE #75: coverage worker
stephan's idea:

when doing `ziggy fuzz` also build a `coverage-worker` target that is compiled exactly the same as `coverage`.
however for this one ziggy runs new inputs from afl/mainaflfuzzer/queue/id:* in the background, and auto-generates the report every 15 minutes.

### PR DESCRIPTION
**Pull request by R9295**
Implements and closes #75 

TODO
- [x] test
- [x] clean up gcda files on restart
- [x] tbd

### CODE REVIEW

**Comment by R9295** [comment]
One doubt I have is if ``fs::read_dir``'s iterator will also continue to yield entries created after it was called (probably?). In that case we may never get to generate the report and may just be stuck running new entries.

**Comment by vanhauser-thc** [comment]
> One doubt I have is if `fs::read_dir`'s iterator will also continue to yield entries created after it was called (probably?). In that case we may never get to generate the report and may just be stuck running new entries.

Test it?

also I deduct this pr still needs quite some real world testing before we merge it? :)

**Comment by R9295** [comment]
Good that I asked:
https://pubs.opengroup.org/onlinepubs/9699919799/functions/readdir.html
https://stackoverflow.com/questions/78185972/does-opendir-findfirstfile-get-a-snapshot-of-a-directory

I'll add another check

**Comment by R9295** [comment]
A suggestion for fuzzer resumes: 
the coverage worker can check the fuzzer_stats file of the main afl node, find it's last update and continue with entries created from that point (if there is no need to reset coverage)

**Pull request merged**
